version: '3.8'
services:
  db:
    image: postgres:17
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  db_data:
